# Generated by Django 4.1.3 on 2022-11-07 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('number', models.PositiveBigIntegerField(default=10000000000000000, verbose_name='Номер карты')),
                ('cvv', models.PositiveSmallIntegerField(verbose_name='CVV код')),
                ('deadline', models.DateField(verbose_name='Срок истечения действия карты')),
            ],
            options={
                'verbose_name': 'Банковская карта',
                'verbose_name_plural': 'Банковские карты',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.CharField(max_length=255, verbose_name='Емеил')),
                ('phone', models.PositiveBigIntegerField(default=89000000000, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Курьер',
                'verbose_name_plural': 'Курьеры',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('login', models.CharField(max_length=255, verbose_name='Логин')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('email', models.CharField(max_length=255, verbose_name='Емеил')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
            },
        ),
        migrations.CreateModel(
            name='Getting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Точка выдачи')),
            ],
            options={
                'verbose_name': 'Способ получения',
                'verbose_name_plural': 'Способы получения',
            },
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Оплата')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплата',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('time', models.CharField(max_length=255, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Точка доставки',
                'verbose_name_plural': 'Точки доставки',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='StatusOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price_product', models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Цена продукта')),
                ('price_purchase', models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Цена закупки')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('image', models.ImageField(upload_to='product/', verbose_name='Изображение')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.color', verbose_name='Цвет')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.size', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Стоимость')),
                ('weight', models.PositiveSmallIntegerField(default=0, verbose_name='Вес')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.customer', verbose_name='Заказчик')),
                ('getting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.getting', verbose_name='Способ получения')),
                ('pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.pay', verbose_name='Оплата')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.point', verbose_name='Точка выдачи')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.statusorder', verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата доставки')),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Стоимость доставки')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.courier', verbose_name='Курьер')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='basket',
            field=models.ManyToManyField(related_name='customer_basket', to='bank.product', verbose_name='В корзине'),
        ),
        migrations.AddField(
            model_name='customer',
            name='card',
            field=models.ManyToManyField(related_name='customer_card', to='bank.card', verbose_name='Банковская карта'),
        ),
        migrations.AddField(
            model_name='customer',
            name='favorite',
            field=models.ManyToManyField(related_name='customer_favorite', to='bank.product', verbose_name='В сохраненных'),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.gender', verbose_name='Пол'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('rating', models.PositiveSmallIntegerField(default=0, verbose_name='Рейтинг')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.customer', verbose_name='Покупатель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.product', verbose_name='Продукт')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.comment', verbose_name='Ответы на комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
